//////////////////////////////////////////////////////////////////////////////////
// AS501/AS603                                                                  //
// TESTBENCH FOR LSTM INFERENCE PROGRAM                                         //
//////////////////////////////////////////////////////////////////////////////////

module CORE_TB();
    localparam DWidth        = 32;

    // IMEM offsets (word address space)
    localparam IMEM_START_W  = 32'h0000_0000;
    localparam IMEM_DEPTH_W  = 32'h0000_8000; // 128KB

    // DMEM offsets (word address space)
    localparam DMEM_START_W  = 32'h0008_0000; // byte 0x0020_0000
    localparam DMEM_DEPTH_W  = 32'h0040_0000; // 16MB

    // IOMEM offsets (word address space)
    localparam IOMEM_START_W = 32'h0800_0000; // byte 0x2000_0000
    localparam IOMEM_DEPTH_W = 32'h0002_0000; // 512KB

    // SPM offsets (word address space)
    localparam SPM_START_W   = 32'h0820_0000; // byte 0x2080_0000
    localparam SPM_DEPTH_W   = 32'h0000_4000; // 16384 words = 64KB

    // DMA controller offsets (word address space)
    localparam DMA_START_W   = 32'h0824_0000; // byte 0x2090_0000
    localparam DMA_DEPTH_W   = 32'h0000_0010; // 16 registers
    localparam InputStart    = 32'h0000_0000;
    localparam ResultStart   = 32'h0000_7fe1; // (_sresult - _sinput) / 4 — .input section empty for TF

    // If main returns, start.s jumps to hang at this PC.
    localparam HANG_PC       = 32'h0000_0034;
    localparam int MAX_CYCLES = 0;         // 0 disables timeout
    localparam int PROGRESS_CYCLES = 500000;
    localparam bit TRACE_PROGRESS = 1'b0;  // disable periodic progress logs by default
    localparam bit TRACE_INST = 1'b0;      // disable per-instruction trace
    localparam bit TRACE_FUNC = 1'b1;      // print only when PC reaches function entry
    localparam int LSTM_STEP_LOG_EVERY = 1000;
    // run_vcs.sh executes simv inside sim/out, so keep dump paths local to CWD.
    localparam string PARTIAL_DUMP_FILE = "lstm_result_summary.txt";

    // result section word layout from program/test_code/result.c
    localparam int RESULT_W_STATUS = 0;
    localparam int RESULT_W_SENT_CNT = 1;
    localparam int RESULT_W_USED_U32 = 2;

    // Function entry addresses from program/out/eval_int_riscv.dis (Transformer)
    localparam logic [31:0] PC_MAIN                    = 32'h0000_2b38;
    localparam logic [31:0] PC_LAYER_NORM              = 32'h0000_0040; // layer_norm_q12.constprop.0
    localparam logic [31:0] PC_MULTI_HEAD_ATTENTION    = 32'h0000_049c; // multi_head_attention
    localparam logic [31:0] PC_ARENA_RESET             = 32'h0000_2d50;
    localparam logic [31:0] PC_ARENA_ALLOC             = 32'h0000_2d74;

    // HEX files generated by `make hex`
    localparam IMEMHexFile   = "../../program_DH_TF/out/eval_int_riscv_imem.hex";
    localparam DMEMHexFile   = "../../program_DH_TF/out/eval_int_riscv_dmem.hex";
    localparam InputHexFile  = "../../program_DH_TF/out/eval_int_riscv_input.hex";
    localparam ResultHexFile = "../../program_DH_TF/out/eval_int_riscv_result.hex";

    // Clocks & reset
    logic clk, rst_n;
    localparam ClkPeriod = 10.0;
    localparam ClkHalf   = ClkPeriod / 2;
    longint unsigned total_cycles = 0;
    initial begin
        clk = 0;
        forever begin
            #ClkHalf clk = ~clk;
        end
    end
    // Count full clock cycles at posedge only.
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) total_cycles <= '0;
        else        total_cycles <= total_cycles + 1;
    end

    // Wave dump for Verdi debug
    // initial begin
        // $fsdbDumpfile("lstm.fsdb");
        // $fsdbDumpvars(0, CORE_TB);
    // end

    // IMEM <-> CPU_TOP
    logic                   imem_req;
    logic [DWidth-1:0]      imem_addr;
    logic [DWidth-1:0]      imem_rdata;

    // DMEM <-> CPU_TOP
    logic                   dmem_req;
    logic                   dmem_write;
    logic [DWidth-1:0]      dmem_addr;
    logic [DWidth-1:0]      dmem_wdata;
    logic [DWidth-1:0]      dmem_rdata;

    // IOMEM <-> CPU_TOP
    logic                   iomem_req;
    logic                   iomem_write;
    logic [DWidth-1:0]      iomem_addr;
    logic [DWidth-1:0]      iomem_wdata;
    logic [DWidth-1:0]      iomem_rdata;

    // For counting instruction fetch requests
    logic icache_read;
    logic icr_q;
    longint unsigned fetch_req_cnt;
    longint unsigned mha_hit_cnt;
    longint unsigned ln_hit_cnt;
    int last_dumped_sentence_cnt;
    int last_dumped_used_u32;
    int wall_start_sec;
    int wall_end_sec;
    int wall_elapsed_sec;
    real wall_elapsed_hour;

    // DUT
    CPU_TOP #(
        .DWidth        (DWidth),
        .IMEM_START_W  (IMEM_START_W),
        .IMEM_DEPTH_W  (IMEM_DEPTH_W),
        .DMEM_START_W  (DMEM_START_W),
        .DMEM_DEPTH_W  (DMEM_DEPTH_W),
        .IOMEM_START_W (IOMEM_START_W),
        .IOMEM_DEPTH_W (IOMEM_DEPTH_W),
        .SPM_START_W   (SPM_START_W),
        .SPM_DEPTH_W   (SPM_DEPTH_W),
        .DMA_START_W   (DMA_START_W),
        .DMA_DEPTH_W   (DMA_DEPTH_W)
    ) DUT (
        .clk_i         (clk),
        .rst_ni        (rst_n),

        .imem_rdata_i  (imem_rdata),
        .imem_addr_o   (imem_addr),
        .imem_req_o    (imem_req),

        .dmem_rdata_i  (dmem_rdata),
        .dmem_wdata_o  (dmem_wdata),
        .dmem_addr_o   (dmem_addr),
        .dmem_req_o    (dmem_req),
        .dmem_write_o  (dmem_write),

        .iomem_rdata_i (iomem_rdata),
        .iomem_wdata_o (iomem_wdata),
        .iomem_addr_o  (iomem_addr),
        .iomem_req_o   (iomem_req),
        .iomem_write_o (iomem_write),

        .icache_read_o (icache_read)
    );

    // Memories
    I_MEMORY #(
        .DWidth        (DWidth),
        .IMEM_START_W  (IMEM_START_W),
        .IMEM_DEPTH_W  (IMEM_DEPTH_W),
        .IMEMHexFile   (IMEMHexFile)
    ) IMEM (
        .clk_i         (clk),
        .rst_ni        (rst_n),
        .imem_req_i    (imem_req),
        .imem_addr_i   (imem_addr),
        .imem_rdata_o  (imem_rdata)
    );

    D_MEMORY #(
        .DWidth        (DWidth),
        .DMEM_START_W  (DMEM_START_W),
        .DMEM_DEPTH_W  (DMEM_DEPTH_W),
        .DMEMHexFile   (DMEMHexFile)
    ) DMEM (
        .clk_i         (clk),
        .rst_ni        (rst_n),
        .dmem_req_i    (dmem_req),
        .dmem_write_i  (dmem_write),
        .dmem_wdata_i  (dmem_wdata),
        .dmem_addr_i   (dmem_addr),
        .dmem_rdata_o  (dmem_rdata)
    );

    IO_MEMORY #(
        .DWidth        (DWidth),
        .IOMEM_START_W (IOMEM_START_W),
        .IOMEM_DEPTH_W (IOMEM_DEPTH_W),
        .InputStart    (InputStart),
        .ResultStart   (ResultStart),
        .InputHexFile  (InputHexFile),
        .ResultHexFile (ResultHexFile)
    ) IOMEM (
        .clk_i         (clk),
        .rst_ni        (rst_n),
        .iomem_req_i   (iomem_req),
        .iomem_write_i (iomem_write),
        .iomem_wdata_i (iomem_wdata),
        .iomem_addr_i  (iomem_addr),
        .iomem_rdata_o (iomem_rdata)
    );

    logic mcu_imem_ready;
    assign mcu_imem_ready = DUT.MCU_INST.imem_ready_o;

    function automatic string opcode_name(input logic [6:0] opc);
        case (opc)
            7'b0110111: opcode_name = "LUI";
            7'b0010111: opcode_name = "AUIPC";
            7'b1101111: opcode_name = "JAL";
            7'b1100111: opcode_name = "JALR";
            7'b1100011: opcode_name = "BRANCH";
            7'b0000011: opcode_name = "LOAD";
            7'b0100011: opcode_name = "STORE";
            7'b0010011: opcode_name = "OP-IMM";
            7'b0110011: opcode_name = "OP";
            7'b0001111: opcode_name = "FENCE";
            7'b1110011: opcode_name = "SYSTEM";
            default:    opcode_name = "UNKNOWN";
        endcase
    endfunction

    function automatic logic [31:0] result_u32_at(input int unsigned u32_idx);
        int unsigned widx;
        begin
            // result section layout: [status, sentence_cnt, used_u32, data...]
            widx = ResultStart + 3 + u32_idx;
            result_u32_at = IOMEM.mem[widx];
        end
    endfunction

    task automatic dump_partial_result_text(input int unsigned sent_cnt, input int unsigned used_u32);
        int fd;
        int unsigned cursor;
        int unsigned s;
        int unsigned k;
        int unsigned seq_len;
        logic [31:0] tok;
        begin
            fd = $fopen(PARTIAL_DUMP_FILE, "w");
            if (!fd) begin
                $display("[TB][warn] Could not open partial dump file: %s", PARTIAL_DUMP_FILE);
                disable dump_partial_result_text;
            end

            $fdisplay(fd, "status=%0d", IOMEM.mem[ResultStart + RESULT_W_STATUS]);
            $fdisplay(fd, "sentence_count=%0d", sent_cnt);
            $fdisplay(fd, "used=%0d", used_u32);
            cursor = 0;
            for (s = 0; s < sent_cnt; s = s + 1) begin
                if (cursor >= used_u32) begin
                    $fdisplay(fd, "sent[%0d].len=<truncated>", s);
                    break;
                end
                seq_len = result_u32_at(cursor);
                cursor = cursor + 1;
                $fdisplay(fd, "sent[%0d].len=%0d", s, seq_len);
                $fwrite(fd, "sent[%0d].tok=", s);
                for (k = 0; k < seq_len; k = k + 1) begin
                    if (cursor >= used_u32) begin
                        break;
                    end
                    tok = result_u32_at(cursor);
                    cursor = cursor + 1;
                    if (k != 0) begin
                        $fwrite(fd, " ");
                    end
                    $fwrite(fd, "%0d", tok);
                end
                $fwrite(fd, "\n");
            end
            $fclose(fd);
        end
    endtask

    // Read Unix epoch seconds from a text file generated by `date +%s`.
    task automatic read_epoch_sec_file(
        input string epoch_file,
        output int epoch_sec,
        output bit ok
    );
        integer fp;
        integer nread;
        begin
            ok = 1'b0;
            epoch_sec = 0;
            fp = $fopen(epoch_file, "r");
            if (fp != 0) begin
                nread = $fscanf(fp, "%d", epoch_sec);
                $fclose(fp);
                if (nread == 1) begin
                    ok = 1'b1;
                end
            end
        end
    endtask

    int exit_signal = 0;
    int exit_reason = 0; // 1: hang-loop reached, 2: timeout
    always @(posedge clk) begin
        if (!exit_signal && mcu_imem_ready && imem_addr == HANG_PC) begin
            $display("[INFO] time=%0t Hang loop reached at PC=0x%08h (main returned).", $time, HANG_PC);
            exit_signal <= 1;
            exit_reason <= 1;
        end
        if (!exit_signal && (MAX_CYCLES > 0) && (total_cycles >= MAX_CYCLES)) begin
            $display("[WARN] Timeout reached at cycle=%0d.", total_cycles);
            exit_signal <= 1;
            exit_reason <= 2;
        end
    end

    // Count instruction fetch requests (edge count)
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            icr_q         <= 1'b0;
            fetch_req_cnt <= '0;
        end else begin
            icr_q <= DUT.icache_read_o;
            if (DUT.icache_read_o & ~icr_q) begin
                fetch_req_cnt <= fetch_req_cnt + 1;
            end
        end
    end

    // Confirm IMEM contents were loaded from hex.
    initial begin
        wait (rst_n === 1'b1);
        #50;
        $display("[TB] IMEM[0..7] = %08h %08h %08h %08h %08h %08h %08h %08h",
            IMEM.mem[0], IMEM.mem[1], IMEM.mem[2], IMEM.mem[3],
            IMEM.mem[4], IMEM.mem[5], IMEM.mem[6], IMEM.mem[7]);
    end

    // Periodic heartbeat for long runs.
    always @(posedge clk) begin
        if (TRACE_PROGRESS && rst_n && (PROGRESS_CYCLES > 0) &&
            ((total_cycles % PROGRESS_CYCLES) == 0) && !exit_signal) begin
            $display("[TB][progress] cycle=%0d time=%0t pc=0x%08h imem_acc=%0d dmem_acc=%0d iomem_acc=%0d",
                total_cycles, $time, imem_addr, IMEM.access_cnt, DMEM.access_cnt, IOMEM.access_cnt);
        end
    end

    // Persist partial decoded result every time result_sentence_count advances.
    always @(posedge clk) begin
        int unsigned sent_cnt_now;
        int unsigned used_u32_now;
        if (!rst_n) begin
            last_dumped_sentence_cnt <= -1;
            last_dumped_used_u32 <= -1;
        end else if (!exit_signal) begin
            sent_cnt_now = IOMEM.mem[ResultStart + RESULT_W_SENT_CNT];
            used_u32_now = IOMEM.mem[ResultStart + RESULT_W_USED_U32];
            if (((int'(sent_cnt_now)) != last_dumped_sentence_cnt) ||
                ((int'(used_u32_now)) != last_dumped_used_u32)) begin
                dump_partial_result_text(sent_cnt_now, used_u32_now);
                last_dumped_sentence_cnt <= int'(sent_cnt_now);
                last_dumped_used_u32 <= int'(used_u32_now);
                $display("[TB] partial result saved: sent_cnt=%0d used_u32=%0d file=%s",
                    sent_cnt_now, used_u32_now, PARTIAL_DUMP_FILE);
            end
        end
    end

    // Instruction trace (LAB1-style): print fetched instruction and PC.
    always @(posedge clk) begin
        if (TRACE_INST && rst_n && mcu_imem_ready) begin
            $display("[TB][inst] time=%0t instruction=0x%08h at address=0x%08h opc=%s",
                $time, imem_rdata, imem_addr, opcode_name(imem_rdata[6:0]));
        end
    end

    // Function-entry trace (PC-based) — Transformer
    always @(posedge clk) begin
        if (TRACE_FUNC && rst_n && mcu_imem_ready) begin
            case (imem_addr)
                PC_MAIN:                   $display("[TB][func] time=%0t pc=0x%08h main", $time, imem_addr);
                PC_MULTI_HEAD_ATTENTION: begin
                    mha_hit_cnt <= mha_hit_cnt + 1;
                    if ((mha_hit_cnt < 40) || ((mha_hit_cnt % 100) == 0))
                        $display("[TB][func] cycle=%0d (%0.3fB) time=%0t pc=0x%08h multi_head_attention count=%0d",
                                 total_cycles, (total_cycles / 1.0e9), $time, imem_addr, mha_hit_cnt + 1);
                end
                PC_LAYER_NORM: begin
                    ln_hit_cnt <= ln_hit_cnt + 1;
                    if ((ln_hit_cnt < 20) || ((ln_hit_cnt % 500) == 0))
                        $display("[TB][func] cycle=%0d time=%0t pc=0x%08h layer_norm count=%0d",
                                 total_cycles, $time, imem_addr, ln_hit_cnt + 1);
                end
                PC_ARENA_RESET:            $display("[TB][func] time=%0t pc=0x%08h arena_reset", $time, imem_addr);
                PC_ARENA_ALLOC:            $display("[TB][func] time=%0t pc=0x%08h arena_alloc", $time, imem_addr);
                default: ;
            endcase
        end
    end

    integer dump_file;
    initial begin
        bit wall_start_ok;
        bit wall_end_ok;
        int wall_cmd_status;
        real total_cycles_b;
        mha_hit_cnt = 0;
        ln_hit_cnt = 0;
        last_dumped_sentence_cnt = -1;
        last_dumped_used_u32 = -1;
        wall_start_sec = 0;
        wall_end_sec = 0;
        wall_elapsed_sec = 0;
        wall_elapsed_hour = 0.0;
        rst_n = 1'b1;
        #10 rst_n = 1'b0;
        #10 rst_n = 1'b1;

        // Measure real-world simulation runtime (host wall-clock time).
        wall_cmd_status = $system("date +%s > tb_wall_start_epoch.txt");
        if (wall_cmd_status == 0) begin
            read_epoch_sec_file("tb_wall_start_epoch.txt", wall_start_sec, wall_start_ok);
            if (wall_start_ok) begin
                $display("[TESTBENCH] Wall-clock start (epoch sec): %0d", wall_start_sec);
            end else begin
                $display("[TB][warn] Failed to read wall-clock start file.");
            end
        end else begin
            $display("[TB][warn] Failed to execute date command for wall-clock start.");
        end

        forever begin
            @(posedge clk);
            if (exit_signal) begin
                if (exit_reason == 1) begin
                    $display("[TESTBENCH] Exit reason: main returned (hang loop).");
                end else if (exit_reason == 2) begin
                    $display("[TESTBENCH] Exit reason: timeout.");
                end
                total_cycles_b = total_cycles / 1.0e9;
                $display("\n[TESTBENCH] Simulation finished.");
                $display("\n[1] Performance");
                $display(" * Total cycles = %0d (%0.3fB)", total_cycles, total_cycles_b);
                $display(" * Total instruction fetch requests = %0d", fetch_req_cnt);
                if (fetch_req_cnt != 0) begin
                    $display(" * CPI = %0f", total_cycles / (fetch_req_cnt * 1.0));
                end
                $display(" * Total multi_head_attention entries (PC-based) = %0d", mha_hit_cnt);
                $display(" * Total layer_norm entries (PC-based) = %0d", ln_hit_cnt);

                $display("\n[2] Memory Access");
                $display(" * Total IMEM accesses = %0d", IMEM.access_cnt);
                $display(" * Total DMEM accesses = %0d", DMEM.access_cnt);
                $display(" * Total IOMEM accesses = %0d", IOMEM.access_cnt);
                $display(" * Total memory accesses = %0d", IMEM.access_cnt + DMEM.access_cnt + IOMEM.access_cnt);

                $display("\n[3] Result Header");
                $display(" * result_status       = 0x%08h", IOMEM.mem[ResultStart + RESULT_W_STATUS]);
                $display(" * result_sentence_cnt = 0x%08h", IOMEM.mem[ResultStart + RESULT_W_SENT_CNT]);
                $display(" * result_used_u32     = 0x%08h", IOMEM.mem[ResultStart + RESULT_W_USED_U32]);

                dump_file = $fopen("lstm_iomem_dump.txt", "w");
                if (dump_file) begin
                    // Dump first 64 words from result region for quick inspection.
                    for (int i = 0; i < 64; i = i + 1) begin
                        $fdisplay(dump_file, "ADDR[0x%08h]: 0x%08h", ((IOMEM_START_W + ResultStart + i) << 2), IOMEM.mem[ResultStart + i]);
                    end
                    $fclose(dump_file);
                    $display("[TESTBENCH] Dumped result region to ./lstm_iomem_dump.txt");
                end else begin
                    $display("[ERROR] Could not open dump file.");
                end

                wall_cmd_status = $system("date +%s > tb_wall_end_epoch.txt");
                if (wall_cmd_status == 0) begin
                    read_epoch_sec_file("tb_wall_end_epoch.txt", wall_end_sec, wall_end_ok);
                    if (wall_end_ok && (wall_start_sec > 0) && (wall_end_sec >= wall_start_sec)) begin
                        wall_elapsed_sec = wall_end_sec - wall_start_sec;
                        wall_elapsed_hour = wall_elapsed_sec / 3600.0;
                        $display("\n[4] Wall-Clock Runtime");
                        $display(" * wall_start_epoch_sec = %0d", wall_start_sec);
                        $display(" * wall_end_epoch_sec   = %0d", wall_end_sec);
                        $display(" * elapsed_sec          = %0d", wall_elapsed_sec);
                        $display(" * elapsed_hour         = %0.4f", wall_elapsed_hour);
                    end else begin
                        $display("[TB][warn] Failed to compute wall-clock elapsed time.");
                    end
                end else begin
                    $display("[TB][warn] Failed to execute date command for wall-clock end.");
                end

                #1;
                $finish;
            end
        end
    end

endmodule
