// Auto-generated by train_transformer.py
// Softermax: barrel shift + linear interp (no exp LUT needed)
#ifndef INT_MODEL_TRANSFORMER_Q12_H
#define INT_MODEL_TRANSFORMER_Q12_H
#include <stdint.h>
#define MODEL_Q_BITS        12
#define MODEL_Q_SCALE       (1 << MODEL_Q_BITS)
#define TF_D_MODEL          128
#define TF_N_HEADS          4
#define TF_D_HEAD           (TF_D_MODEL / TF_N_HEADS)
#define TF_D_FF             256
#define TF_N_ENC_LAYERS     2
#define TF_N_DEC_LAYERS     2
#define TF_MAX_SRC_LEN      40
#define TF_MAX_TGT_LEN      40
#define TF_ATTN_SCALE_Q     724
#define TF_LN_EPS_Q         1
#define TF_POW2_MIN_SHIFT   12
#define TF_EXP_X_MIN_Q     (-8 * MODEL_Q_SCALE)
#define MODEL_SRC_VOCAB     18726
#define MODEL_TGT_VOCAB     10214
extern const int32_t pos_enc_q[40 * TF_D_MODEL];
extern const int32_t enc_emb_q[MODEL_SRC_VOCAB * TF_D_MODEL];
extern const int32_t dec_emb_q[MODEL_TGT_VOCAB * TF_D_MODEL];
extern const int32_t out_w_q[MODEL_TGT_VOCAB * TF_D_MODEL];
extern const int32_t out_b_q[MODEL_TGT_VOCAB];
extern const int32_t enc_attn_Wq_q[TF_N_ENC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t enc_attn_bq_q[TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_attn_Wk_q[TF_N_ENC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t enc_attn_bk_q[TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_attn_Wv_q[TF_N_ENC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t enc_attn_bv_q[TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_attn_Wo_q[TF_N_ENC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t enc_attn_bo_q[TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_ff1_W_q[TF_N_ENC_LAYERS * TF_D_FF    * TF_D_MODEL];
extern const int32_t enc_ff1_b_q[TF_N_ENC_LAYERS * TF_D_FF];
extern const int32_t enc_ff2_W_q[TF_N_ENC_LAYERS * TF_D_MODEL * TF_D_FF];
extern const int32_t enc_ff2_b_q[TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_ln1_gamma_q[TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_ln1_beta_q [TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_ln2_gamma_q[TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_ln2_beta_q [TF_N_ENC_LAYERS * TF_D_MODEL];
extern const int32_t enc_final_ln_gamma_q[TF_D_MODEL];
extern const int32_t enc_final_ln_beta_q [TF_D_MODEL];
extern const int32_t dec_self_Wq_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_self_bq_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_self_Wk_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_self_bk_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_self_Wv_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_self_bv_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_self_Wo_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_self_bo_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_cross_Wq_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_cross_bq_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_cross_Wk_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_cross_bk_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_cross_Wv_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_cross_bv_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_cross_Wo_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_MODEL];
extern const int32_t dec_cross_bo_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_ff1_W_q[TF_N_DEC_LAYERS * TF_D_FF    * TF_D_MODEL];
extern const int32_t dec_ff1_b_q[TF_N_DEC_LAYERS * TF_D_FF];
extern const int32_t dec_ff2_W_q[TF_N_DEC_LAYERS * TF_D_MODEL * TF_D_FF];
extern const int32_t dec_ff2_b_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_ln1_gamma_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_ln1_beta_q [TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_ln2_gamma_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_ln2_beta_q [TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_ln3_gamma_q[TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_ln3_beta_q [TF_N_DEC_LAYERS * TF_D_MODEL];
extern const int32_t dec_final_ln_gamma_q[TF_D_MODEL];
extern const int32_t dec_final_ln_beta_q [TF_D_MODEL];
#endif
